## Getting and Cleaning Data Course Project Code Book

### Original Raw Data
Original data is from smartphone accelerometer and gyroscope 3-axial raw signals, which have been processed using various signal processing techniques to a measurement vector consisting of 561 parameters. A detailed description fo the original dataset is available in the original data archive in a file called "features_info.txt" 

The data is available at this link:
[Original Raw Data](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

A description of this data is available at this link:
[Description of data](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

Information specifying the raw data format is inclued in the Further Information section at the bottom on this document.

### Working Data
The working data was a subset of the original raw data, selected by filtering only data relating to the mean and standard deviation of measurements.  This was achieved by selecting data with names containing "mean" and "std" only.  Note that is the absence of instructions to ignore Mean Frequency 'meanFreq' data was also retained in the Tidy Dataset.  

This reduced the Original Raw Data with 563 variables (561 measurement variables) to a subset with 81 variables (78 measurement variables and 3 identifier variables).  

The training and test datasets were combined to produce a final working dataset

### Tidy Data
Tidy working data was delivered by splitting the working data into subsets based on subject and activity, and computing summary means of each variable for each activity by subject. Descriptive activity labels are merged into the dtaset from the information detailed in activity_label.txt available in the original raw data archive. The original variable names were modified to make them more descriptive and readable by taking the following actions:

* Empty parenthesis '()' is removed 
* "-std" is replaced by "StandardDeviation"
* "-mean" is replaced by "Mean"
* "BodyBody"is replaced by "Body"
* "Mag"is replaced by "Magnitude"
* "Freq"is replaced by "Frequency"
* "-X" is replaced by "X"
* "-Y"is replaced by "Y"
* "-Z" is replaced by "Z"


A sample of how the modified variable names compare to original variable name in the raw data is detailed below:

Raw data variable names | Tidy data variable names
---------|----------
tBodyAcc-mean()-Y | tBodyAccMeanY
tBodyAcc-std()-Z | tBodyAccStandardDeviationZ
tBodyGyroJerk-mean()-Y | tBodyGyroJerkMeanY
fBodyBodyGyroMag-meanFreq() | fBodyGyroMagnitudeMeanFrequency

### Further Information relating to the Original Raw Data
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag

**Note that these variable names are modified ain the Tidy Data, as explained above.**

The set of variables that were estimated from these signals are: 

* mean(): Mean value
* std(): Standard deviation
* mad(): Median absolute deviation 
* max(): Largest value in array
* min(): Smallest value in array
* sma(): Signal magnitude area
* energy(): Energy measure. Sum of the squares divided by the number of values. 
* iqr(): Interquartile range 
* entropy(): Signal entropy
* arCoeff(): Autorregresion coefficients with Burg order equal to 4
* correlation(): correlation coefficient between two signals
* maxInds(): index of the frequency component with largest magnitude
* meanFreq(): Weighted average of the frequency components to obtain a mean frequency
* skewness(): skewness of the frequency domain signal 
* kurtosis(): kurtosis of the frequency domain signal 
* bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
* angle(): Angle between to vectors.

**Only the mean(), meanFreq(), and std() measurement variables are present in the Tidy Data.**

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

* gravityMean
* tBodyAccMean
* tBodyAccJerkMean
* tBodyGyroMean
* tBodyGyroJerkMean

**The complete list of variables of each feature vector is available in 'features.txt'**

11-23-2014
